"""
Gmail SMTP digest sender.

Builds an HTML digest of scored job offers and attaches tailored PDF CVs.
"""

from __future__ import annotations

import logging
import os
import smtplib
from datetime import datetime, timezone
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from src.scorer import ScoredJob

logger = logging.getLogger(__name__)

OUTPUT_DIR = "output"


def _score_badge(score: int) -> str:
    if score >= 8:
        color, label = "#22c55e", "Strong Fit"
    elif score >= 6:
        color, label = "#eab308", "Good Fit"
    elif score >= 4:
        color, label = "#f97316", "Moderate"
    else:
        color, label = "#ef4444", "Weak Fit"
    return (
        f'<span style="background:{color};color:white;padding:2px 8px;'
        f'border-radius:4px;font-size:12px;font-weight:bold;">'
        f"{score}/10 — {label}</span>"
    )


def _job_html(sj: ScoredJob, has_resume: bool) -> str:
    job = sj.listing
    badge = _score_badge(sj.score)
    resume_note = ' 📎 <em>Tailored CV attached</em>' if has_resume else ""
    keywords = ", ".join(sj.keywords[:8]) if sj.keywords else ""
    return f"""
    <div style="border:1px solid #e5e7eb;border-radius:8px;padding:16px;margin-bottom:12px;background:#fafafa;">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
            <strong style="font-size:16px;">{job.title}</strong>
            {badge}
        </div>
        <div style="color:#6b7280;font-size:14px;margin-bottom:8px;">
            {job.company} &middot; {job.location} &middot; via {job.source}
        </div>
        <div style="font-size:13px;color:#374151;margin-bottom:8px;">{sj.summary}</div>
        <div style="font-size:13px;color:#6b7280;margin-bottom:8px;"><em>{sj.comment}</em></div>
        <div style="font-size:12px;color:#6b7280;margin-bottom:4px;">
            <strong>Keywords:</strong> {keywords}
        </div>
        <div style="margin-top:8px;">
            <a href="{job.url}" style="color:#2563eb;text-decoration:none;font-weight:bold;">
                View & Apply →
            </a>{resume_note}
        </div>
    </div>
    """


def build_digest_html(
    scored_jobs: list[ScoredJob], resume_map: dict[str, str], config: dict
) -> str:
    now = datetime.now(timezone.utc)
    hour = now.hour
    label = config.get("email", {}).get(
        "morning_label" if hour < 18 else "evening_label", "Update"
    )

    total = len(scored_jobs)
    high_score = sum(1 for sj in scored_jobs if sj.score >= 8)
    tailored = len(resume_map)

    top = [sj for sj in scored_jobs if sj.score >= 8]
    mid = [sj for sj in scored_jobs if 5 <= sj.score < 8]
    low = [sj for sj in scored_jobs if sj.score < 5]

    sections = ""
    if top:
        sections += '<h2 style="color:#16a34a;margin-top:24px;">🎯 Top Matches (8+)</h2>'
        for sj in top:
            sections += _job_html(sj, sj.listing.job_id in resume_map)
    if mid:
        sections += '<h2 style="color:#ca8a04;margin-top:24px;">👀 Worth a Look (5-7)</h2>'
        for sj in mid:
            sections += _job_html(sj, False)
    if low:
        sections += '<h2 style="color:#9ca3af;margin-top:24px;">📋 Other Listings</h2>'
        for sj in low:
            sections += _job_html(sj, False)

    return f"""
    <html>
    <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:680px;margin:0 auto;padding:20px;">
        <div style="background:linear-gradient(135deg,#1e3a5f,#2563eb);color:white;padding:24px;border-radius:12px;margin-bottom:24px;">
            <h1 style="margin:0;font-size:24px;">Job Scout — {label} Digest</h1>
            <p style="margin:8px 0 0;opacity:0.9;">
                {now.strftime('%B %d, %Y')} &middot;
                {total} ranked &middot;
                {high_score} strong matches &middot;
                {tailored} CVs tailored
            </p>
        </div>
        {sections}
        <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:12px;">
            Generated by Job Scout &middot; Source: LinkedIn guest API &middot; Ranking: GPT-4o-mini (LangChain)
        </div>
    </body>
    </html>
    """


def _save_digest_locally(html: str) -> str:
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    now = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M")
    path = os.path.join(OUTPUT_DIR, f"digest_{now}.html")
    with open(path, "w") as f:
        f.write(html)
    logger.info(f"Digest saved locally: {path}")
    return path


def send_digest(
    scored_jobs: list[ScoredJob], resume_map: dict[str, str], config: dict
) -> None:
    gmail_address = os.environ.get("GMAIL_ADDRESS")
    gmail_password = os.environ.get("GMAIL_APP_PASSWORD")
    to_address = config.get("email", {}).get("to", gmail_address)
    subject_prefix = config.get("email", {}).get("subject_prefix", "[Job Scout]")

    html = build_digest_html(scored_jobs, resume_map, config)

    if not gmail_address or not gmail_password:
        logger.error("Gmail credentials not set — saving locally instead")
        _save_digest_locally(html)
        return

    now = datetime.now(timezone.utc)
    subject = f"{subject_prefix} {len(scored_jobs)} listings — {now.strftime('%b %d')}"

    msg = MIMEMultipart()
    msg["From"] = gmail_address
    msg["To"] = to_address
    msg["Subject"] = subject
    msg.attach(MIMEText(html, "html"))

    for _job_id, pdf_path in resume_map.items():
        if os.path.exists(pdf_path):
            with open(pdf_path, "rb") as f:
                attachment = MIMEApplication(f.read(), _subtype="pdf")
                attachment.add_header(
                    "Content-Disposition",
                    "attachment",
                    filename=os.path.basename(pdf_path),
                )
                msg.attach(attachment)

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_address, gmail_password)
            server.send_message(msg)
        logger.info(f"Digest sent to {to_address} with {len(resume_map)} attachments")
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        _save_digest_locally(html)
