"""
Email digest module.
Sends a formatted HTML email with scored job listings and attached resumes.
Uses Gmail SMTP with App Password authentication.
"""

import logging
import os
import smtplib
from datetime import datetime, timezone
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from src.scorer import ScoredJob

logger = logging.getLogger(__name__)


def _score_badge(score: int) -> str:
    """Generate an HTML badge for the fit score."""
    if score >= 8:
        color = "#22c55e"  # green
        label = "Strong Fit"
    elif score >= 6:
        color = "#eab308"  # yellow
        label = "Good Fit"
    elif score >= 4:
        color = "#f97316"  # orange
        label = "Moderate"
    else:
        color = "#ef4444"  # red
        label = "Weak Fit"

    return (
        f'<span style="background:{color};color:white;padding:2px 8px;'
        f'border-radius:4px;font-size:12px;font-weight:bold;">'
        f'{score}/10 — {label}</span>'
    )


def _build_job_html(scored_job: ScoredJob, has_resume: bool) -> str:
    """Build HTML for a single job listing."""
    job = scored_job.listing
    badge = _score_badge(scored_job.score)
    resume_note = ' 📎 <em>Tailored resume attached</em>' if has_resume else ''

    return f"""
    <div style="border:1px solid #e5e7eb;border-radius:8px;padding:16px;margin-bottom:12px;background:#fafafa;">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
            <strong style="font-size:16px;">{job.title}</strong>
            {badge}
        </div>
        <div style="color:#6b7280;font-size:14px;margin-bottom:8px;">
            {job.company} &middot; {job.location} &middot; via {job.source}
        </div>
        <div style="font-size:13px;color:#374151;margin-bottom:8px;">
            {scored_job.reasoning}
        </div>
        <div style="font-size:12px;color:#6b7280;margin-bottom:4px;">
            <strong>Variant:</strong> {scored_job.variant} &middot;
            <strong>Keywords:</strong> {scored_job.tailoring_notes[:150]}
        </div>
        <div style="margin-top:8px;">
            <a href="{job.url}" style="color:#2563eb;text-decoration:none;font-weight:bold;">
                View & Apply →
            </a>
            {resume_note}
        </div>
    </div>
    """


def build_digest_html(
    scored_jobs: list[ScoredJob],
    resume_map: dict[str, str],
    config: dict,
) -> str:
    """Build the full HTML email digest."""
    now = datetime.now(timezone.utc)
    hour = now.hour
    label = config.get("email", {}).get(
        "morning_label" if hour < 18 else "evening_label",
        "Update"
    )

    total = len(scored_jobs)
    high_score = sum(1 for sj in scored_jobs if sj.score >= 7)
    tailored = len(resume_map)

    # Split into tiers
    top_tier = [sj for sj in scored_jobs if sj.score >= 7]
    mid_tier = [sj for sj in scored_jobs if 4 <= sj.score < 7]
    low_tier = [sj for sj in scored_jobs if sj.score < 4]

    sections_html = ""

    if top_tier:
        sections_html += '<h2 style="color:#16a34a;margin-top:24px;">🎯 Top Matches (7+)</h2>'
        for sj in top_tier:
            has_resume = sj.listing.job_id in resume_map
            sections_html += _build_job_html(sj, has_resume)

    if mid_tier:
        sections_html += '<h2 style="color:#ca8a04;margin-top:24px;">👀 Worth a Look (4-6)</h2>'
        for sj in mid_tier:
            sections_html += _build_job_html(sj, False)

    if low_tier:
        sections_html += '<h2 style="color:#9ca3af;margin-top:24px;">📋 Other Listings</h2>'
        for sj in low_tier:
            sections_html += _build_job_html(sj, False)

    html = f"""
    <html>
    <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:680px;margin:0 auto;padding:20px;">
        <div style="background:linear-gradient(135deg,#1e3a5f,#2563eb);color:white;padding:24px;border-radius:12px;margin-bottom:24px;">
            <h1 style="margin:0;font-size:24px;">Job Scout — {label} Digest</h1>
            <p style="margin:8px 0 0;opacity:0.9;">
                {now.strftime('%B %d, %Y')} &middot;
                {total} new listings found &middot;
                {high_score} strong matches &middot;
                {tailored} resumes tailored
            </p>
        </div>

        {sections_html}

        <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:12px;">
            Generated by Job Scout Pipeline &middot;
            Sources: Indeed RSS, Adzuna, Arbeitnow, Remotive &middot;
            <a href="https://github.com/KaiyueWei/job-scout">Repo</a>
        </div>
    </body>
    </html>
    """
    return html


def send_digest(
    scored_jobs: list[ScoredJob],
    resume_map: dict[str, str],
    config: dict,
):
    """Send the email digest via Gmail SMTP."""
    gmail_address = os.environ.get("GMAIL_ADDRESS")
    gmail_password = os.environ.get("GMAIL_APP_PASSWORD")
    to_address = config.get("email", {}).get("to", gmail_address)
    subject_prefix = config.get("email", {}).get("subject_prefix", "[Job Scout]")

    if not gmail_address or not gmail_password:
        logger.error("Gmail credentials not set — skipping email")
        _save_digest_locally(scored_jobs, resume_map, config)
        return

    now = datetime.now(timezone.utc)
    subject = f"{subject_prefix} {len(scored_jobs)} listings — {now.strftime('%b %d')}"

    # Build email
    msg = MIMEMultipart()
    msg["From"] = gmail_address
    msg["To"] = to_address
    msg["Subject"] = subject

    # HTML body
    html = build_digest_html(scored_jobs, resume_map, config)
    msg.attach(MIMEText(html, "html"))

    # Attach tailored resumes
    for job_id, pdf_path in resume_map.items():
        if os.path.exists(pdf_path):
            with open(pdf_path, "rb") as f:
                attachment = MIMEApplication(f.read(), _subtype="pdf")
                filename = os.path.basename(pdf_path)
                attachment.add_header("Content-Disposition", "attachment", filename=filename)
                msg.attach(attachment)

    # Send
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_address, gmail_password)
            server.send_message(msg)
        logger.info(f"Digest sent to {to_address} with {len(resume_map)} attachments")
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        _save_digest_locally(scored_jobs, resume_map, config)


def _save_digest_locally(
    scored_jobs: list[ScoredJob],
    resume_map: dict[str, str],
    config: dict,
):
    """Fallback: save digest as local HTML file."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    html = build_digest_html(scored_jobs, resume_map, config)
    now = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M")
    path = f"output/digest_{now}.html"
    with open(path, 'w') as f:
        f.write(html)
    logger.info(f"Digest saved locally: {path}")


OUTPUT_DIR = "output"
